version: '2'
services:
  redis:
    image: redis:3.2
  postgres:
    image: postgres:9.4
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
